[package]
name = "vault-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
log = "0.4.25"
thiserror = "2.0.11"

[dev-dependencies]
serial_test = "3.1.1"

[lib]
name = "vault_indexer"
path = "src/lib.rs"

[[bin]]
name = "vault-indexer"
path = "src/main.rs"
