[package]
name = "vault-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
serial_test = "3.1.1"

[lib]
name = "vault_indexer"
path = "src/lib.rs"

[[bin]]
name = "vault-indexer"
path = "src/main.rs"